### ISSUE TITLE
# Safety comments

### ISSUE THREAD

**Issue by FrankReh** [emakman/dioxus-shareables#1]
This could be an interesting add-on for users of `dioxus`, thanks for sharing.

Also wanted to say the implementation would be easier to follow if you added `# safety:` comments to the `unsafe` blocks so others could see what invariants were being held. I know the dioxus doesn't always do that either. Some people will be averse to trying this crate if they can't follow what's happening in the `unsafe` blocks. I would offer a PR but I didn't grok the safety invariants myself on the first reading.

Also `cargo clippy` generates a few warnings, probably none actually pointing to problems.

Again, thanks. Reminds me of signals.

Oh, also noticed you use a HashMap. Did you see that `dioxus` uses [rustc-hash](https://crates.io/crates/rustc-hash) for some efficiency gains instead of the std HashMap.

**Comment by emakman** [comment]
* The clippy lints are fixed (no real problem there).
* rustc-hash seems like it's the way to go; I'll switch that out when I get a minute.
* I started adding safety comments, but it's been a second since I looked at this project, and the remaining uncommented unsafe blocks are all accesses to the shared static (which may actually introduce a race condition in async under unlikely use conditions, but are safe without actual concurrency, which I believe means they're safe in dioxus-web and dioxus-desktop?). I'm fairly certain it's a straightforward fix, but I was putting it off until I did some redesign for thread-safety in general.

**Comment by FrankReh** [comment]
Thanks for getting back to me so quickly. Nice that you realize when one isn't fresh with all the workings, it can be hard to figure out if the use of `unsafe` is actually safe. I don't think I mentioned it above, but I expect a lot of churn from `dioxus` for some time to come and that will come with crashes, and it would be nice to be able to rule out UB from this package. So if and when you can get to it, great and thanks again. You can close this issue whenever you like.

**Comment by FrankReh** [comment]
The safety comments are great. Looks much more approachable.
